/// Flutter icons AngelCareIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AngelCareIcons
///      fonts:
///       - asset: fonts/AngelCareIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AngelCareIcons {
  AngelCareIcons._();

  static const _kFontFam = 'AngelCareIcons';
  static const String? _kFontPkg = null;

  static const IconData dashedeye = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lung = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
